### ISSUE TITLE
How to visualize the attention map in FFVT?

### ISSUE THREAD

**Issue by OhJackHu** [Markin-Wang/FFVT#1]

**Comment by Markin-Wang** [comment]
Hi, you can refer to the [vit-pytorch](https://github.com/jeonsworld/ViT-pytorch) repository to see how to visualize the attention map via the visualize_attention_map.ipynb file.
Generally, you need to keep the attention score matrix and then utilize it to generate the attention map.

**Comment by OhJackHu** [comment]
> 
> 
> Hi, you can refer to the [vit-pytorch](https://github.com/jeonsworld/ViT-pytorch) repository to see how to visualize the attention map via the visualize_attention_map.ipynb file. Generally, you need to keep the attention score matrix and then utilize it to generate the attention map.

**Comment by OhJackHu** [comment]
十分感谢！
