### ISSUE TITLE
Which pre-trained model did you use

### ISSUE THREAD

**Issue by mobulan** [Markin-Wang/FFVT#4]
The vit-b_16 
- only pre-trained on imagenet21k or(393mb)
- pre-trained on imagenet21k and fine-tuned on imagenet2012(331mb)

**Comment by Markin-Wang** [comment]
Hi, sorry for the late reply. It is the model pre-trained on the imagenet21k as we mentioned in the paper (the conference version, we also updated the arxiv version which is the same as the BMVC conference). We added the results of FFVT on dogs dataset in the newest version.

Besides, you can use the command "wget https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz" to obtain the pre-trained model which is also shown in readme.

**Comment by mobulan** [comment]
Thanks a lot. Your work is really helpful to me
